version: '3'
services:
  apps:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../:/code
      - /code/.pnpm-store
      - /code/node_modules
      - /code/apps/web/node_modules
      - /code/apps/web/.turbo
      - /code/apps/api/node_modules
      - /code/apps/api/.turbo
      - /code/libs/shared/node_modules
      - /code/libs/shared/.turbo
    ports:
      - '8001:8001'
      - '8000:8000'
    command: pnpm dev 

  proxy:
    image: caddy:2.6.4-alpine
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
