version: '3'
services:
  apps:
    env_file: ../../.env
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../:/code
      - /code/.pnpm-store
      - /code/node_modules
      - /code/apps/web/node_modules
      - /code/apps/web/.turbo
      - /code/apps/api/node_modules
      - /code/apps/api/.turbo
      - /code/libs/shared/node_modules
      - /code/libs/shared/.turbo
    depends_on:
      - db
    command: pnpm dev

  proxy:
    env_file: ../../.env
    image: caddy:2.6.4-alpine
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  db:
    env_file: ../../.env
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - postgres_data:/var/lib/posgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
