version: '3'
services:
  apps:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ../:/code
      - nm:/code/node_modules
      - web_nm:/code/apps/web/node_modules
      - web_turbo:/code/apps/web/.turbo
      - api_nm:/code/apps/api/node_modules
      - api_turbo:/code/apps/api/.turbo
      - shared_nm:/code/libs/shared/node_modules
      - shared_turbo:/code/libs/shared/.turbo
    ports:
      - '8001:8001'
      - '8000:8000'
    command: pnpm dev 

  proxy:
    image: caddy:2.6.4-alpine
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  nm:
  web_nm:
  web_turbo:
  api_nm:
  api_turbo:
  shared_nm:
  shared_turbo:
