# fly.toml app configuration file generated for wad-web on 2023-07-31T17:02:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wad-web"
primary_region = "lhr"

[build]
  dockerfile = "frontend.Dockerfile"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

